[settings]
# configure `mise install` to always keep the downloaded archive
always_keep_download = false
always_keep_install = false
verbose = false

[tools]
tuist = "4.9.0"
swiftlint = "0.53.0" # https://github.com/realm/SwiftLint/releases
