//
//  LegacyDrawingFixture.swift
//  CarveFeatureTest
//
//  Copyright © 2026 leetaek. All rights reserved.
//

import Foundation
import PencilKit

/// Phase 0B 회귀 fixture — 실기기에서 추출한 실제 필사 blob.
///
/// 출처: 실사용 기기 백업(2026-09-05 추출)의 `BibleDrawing.lineData` 225건 중
/// 특성이 겹치지 않는 5건. **어느 본문인지는 의도적으로 기록하지 않습니다**
/// (개인 필사 기록이므로 식별 메타를 제거했습니다).
///
/// 모든 blob 은 **절 로컬 좌표계**입니다 — 추출 시점의 배포 버전이 롤백 이후이기 때문입니다.
/// 1.2.0 `CombinedCanvas` 가 저장했던 **절대좌표** 형식은 저장하지 않고
/// `absoluteVariant(of:verseRect:)` 로 만들어 씁니다. 두 형식의 관계가
/// `normalizedForVerseRect` 의 역변환이라는 점을 코드에 드러내기 위함입니다.
///
/// blob 을 base64 상수로 내장한 이유는 테스트 타깃에 resource 설정이 없어
/// 프로젝트 설정 변경을 피하기 위함입니다 (AGENTS.md: 빌드 설정 변경 금지).
enum LegacyDrawingFixture {

    struct Sample: Sendable {
        /// 사람이 읽기 위한 식별자. 본문 정보를 담지 않습니다.
        let name: String
        /// 이 샘플이 대표하는 특성
        let note: String
        let base64: String
        /// 추출 시점 실측값 — 디코드 결과가 다르면 인코딩 호환성이 깨진 것입니다.
        let expectedStrokeCount: Int
        let expectedBounds: CGRect

        var data: Data { Data(base64Encoded: base64)! }
        func drawing() throws -> PKDrawing { try PKDrawing(data: data) }
    }
    static let single = Sample(
        name: "single",
        note: "단일 획, 최소 크기",
        base64:
            "AXdyZPABAAgAEhAAAAAAAAAAAAAAAAAAAAAAEhDlCftjVFpJA5w0WpmMRF8cGgYIABAAGAAaBggBEAEYASI3ChQNAAAAABUAAAAAHQAAAAAlAACAPxIUY29tLmFwcGxlLmluay5wZW5jaWwYA0EAAAAAAADwvyqw"
            + "AwoQi9fZqVFqQja9AmPB5WCU1BIGCAAQARgBGgYIABABGAAgACrsAgoQUWDxvV7mRDOtis4B0PZ8kxHzO1W1nGPHQRgTIKMCKNwNMhKamZk/6AMCABShtY4AAIA/AAA6sALeyP1B42+jQQAAAACuAHQPfgL0QUEM"
            + "lUEAEoM7zQB+EStQ9UGH94dBgEOLPPAA2RNRzQJCn6iGQeClGz3wANwTjVEJQhxQh0HAzEw98ADcE58dEkJw2o1BYJFtPfAA3BMuVBdCrLOVQXBokT36AIAUZE4YQrq+pEHg+6k9EAEAFgpxEkJKjq5B0MzMPSAB"
            + "BxfDSwpCbra3QRAv3T0uAfUX5tgAQuzxvEGwne89MgFDGKcZ8EEt6L5BAAAAPjMBTBi+8dlBwkC+QSgxCD4yAUMYDHnRQTJxtEEIgRU+EAH6FaCEz0HpjJ1BKLIdPvIAABToStlB1mSUQaAaLz6TAKwNoe7oQXDa"
            + "jUHASzc+VgCXCYQt+0FGlYpBEINAPhsAqwVAtgZC856IQTi0SD4MAKkESAAyFA0AAMBBFQAAcEEdAACAQSUAADBBQMCyxa3WBDoGCAAQABgAQhCMWUNQQuxFDYfdSthO794W"
        ,
        expectedStrokeCount: 1,
        expectedBounds: CGRect(x: 24.0, y: 15.0, width: 16.0, height: 11.0)
    )

    static let aboveOrigin = Sample(
        name: "aboveOrigin",
        note: "절 원점 위로 벗어나는 획 (minY 음수)",
        base64:
            "AXdyZPABAAgAEhAAAAAAAAAAAAAAAAAAAAAAEhCGO6NJWVNGsraaOwkJ7NfHGgYIABAAGAAaBggDEAEYAyI/ChQNAAAAABUAAAAAHQAAAAAlAACAPxIUY29tLmFwcGxlLmluay5tYXJrZXIYAyIGbGluZWFyQQAA"
            + "AAAAAPC/KtMCChDtl0t0gP9MIb60PzoTO/q5EgYIABABGAEaBggAEAEYACAAKvwBChCT+KzGjARNH6NJLL8acAkKERVS1IFRCcdBGAkg6wMolAwyDAAAoEAAAAAAgD8AADrGAaFE6kFmfpZAAAAAAFQFsQD8n9d8"
            + "QjZ79NdBPgFkQIASAzxQBckAhaFdfHk41HPPQXx89z+AEoM8UAUMASGiXXxrPlLX3UEYD+0/YI0XPVAFPgHnoV185UJIMe5Bvt8vQICRbT1QBT8BzKFdfABDl576QVSlc0CAaJE9UAUjAb6hXXyLQLEjBkKDj7BA"
            + "0MqhPVAF6gCzoV18YzuDnw9CqhXiQEBeuj1QBXMAqKFdfLkwvy4VQhXw9kAA/tQ9UAUKALWhXXxTJ0gHMhQNAACoQRUAAEDAHQAAqEElAACAQUCAh7+3iwaCARA3ageWTP5E5ZPHH24+iZUhKvoBChCNlUOi3GBI"
            + "EqmBwySSqXJ4EgYIARABGAIaBggAEAEYACAAKqMBChDb39RpbbtHr4k812YmO8JBEYYe8YFRCcdBGAYg4wIonA0yEAAAoEBQBQAAXXwAAIA/AAA6bFGv1EEETllBAAAAANYA4pqdOQhfwkF5qklBABODOzEBrZrP"
            + "QYER0kGc2EFBgJHtPDYBmJo1QiN14EGc2EFB4MxMPfkAipq9PJwn8EGc2EFBgJFtPaMAfZoRNTQyA0Kwm1pBUDeJPTQAbJoWKzIUDQAAoEEVAADgQB0AAJBBJQAAMEFAoOuotZgFggEQJ8gY/SgpSc+Hl8Z9FHKG"
            + "RirzBQoQaUpr3RVmQM67toBPMMzHoBIGCAIQARgDGgYIABABGAAgACqcBQoQoPBGK4+DShmV4iiu9rhy2xHyegiCUQnHQRgcIOsDKJQMMgwAAKBAAAAAAIA/AAA66ARh3rlB9ySRQQAAAABQBe8AcppdfNU76Cuq"
            + "Qdm3hkEAEoM7UAUoAUqaXXzuQBMFskGerHRBAAisPFAFaQFFml18xEYypMVBaT9qQeClGz1QBWwBQJpdfBlHUtfdQTm7Y0GAajw9UAVsATeaXXwZRx7s6kGMbWJBAC9dPVAFbAEyml18GUdDqPhBjG1iQeCpcT1Q"
            + "BWwBLZpdfBdHBRoIQuYIZUEgBoE9UAVsASOaXXwMRwCREkIi43lBcGiRPVAFYwEcml18Nkb7vRpCM5WMQcDKoT1QBVoBH5pdfHZFJQMeQsLfnEFQObQ9UAVZASOaXXxdReNWHkLtorVBoJvEPU0FYgExmgh8Kkbp"
            + "cxhCO5TGQWA73z1ABXcBP5qHegFIrFAOQnFD1EGwne89NQWQAVOaK3lNSgUaCEKhx9pBAAAAPjAFnQFempZ4fUvyOwFCZlffQZAYBD4sBacBaZoXeF5MxmzzQSrn40FINwk+KQWzAXaarndgTaCw5UGW2+VB2E8N"
            + "PiYFugGBmmJ3Ck7Vm9hBltvlQXBoET4kBb8Bi5ord3xOMhDBQZbb5UEAgRU+IwXBAaCa/natTpXJrEGhx9pBKLIdPiMFwQG0mv52rU6aUqJBETvHQXjpJj4jBbQByZr+do1NcA2fQSgTsUGgGi8+IwWIAeGa/naX"
            + "SXANn0GqnZlBwEs3PiMFQgH1mv52U0OVNahB2beGQRCDQD4jBfUABJv+dm88Yd65QcLabEE4tEg+IwWaAAqb/nZJNNn8xEHgH2FBYOVQPiMFKgAZm/52KionatFBLGVVQRgEVj4jBQYALZv+dgMnMhQNAABwQRUA"
            + "ABBBHQAA8EElAADAQUDA297CwweCARAnyBj9KClJz4eXxn0UcoZGOgYIABAAGABCEGCEAQOkIEOjpaBmHHqD5qU="
        ,
        expectedStrokeCount: 3,
        expectedBounds: CGRect(x: 15.0, y: -3.0, width: 30.0, height: 36.0)
    )

    static let wideLine = Sample(
        name: "wideLine",
        note: "가로로 넓은 한 줄",
        base64:
            "AXdyZPABAAgAEhAAAAAAAAAAAAAAAAAAAAAAEhDtvqWUhTxLTYAjQkWHX6ItGgYIABAAGAAaBggGEAEYBiI3ChQNAAAAABUAAAAAHQAAAAAlAACAPxIUY29tLmFwcGxlLmluay5wZW5jaWwYA0FaOx1/eHjovyqw"
            + "AwoQ2LwcjyYIT32Js+zQxd2LIRIGCAAQARgBGgYIABABGAAgACrsAgoQQbLhrrH8Sf6aWs8/rc02CxHeHgxCpRvHQRgTIKMCKNwNMhLEw8M/6AMJACGTm4MAAIA/AAA6sAJr7hBCQuIuQgAAAACQAHoML18LQqJJ"
            + "OkLgpRs9BwGYE3B3BkKQ0z9CMAisPS4B8RUU2v9BwLZEQoBqvD1PAesXnCfwQa6fSELAzMw9ZwFcGabN30FP7UlCYDvfPXQBHRrUc89BT+1JQrCd7z15AWMaW8G/QQ7zSEIAAAA+eQFjGuOitEETaUNCSDcJPnkB"
            + "YxoSca1Bruo7QnBoET5oAWgZQtOqQZseM0KYmRk+TAG6F0LTqkHppSpC4NAiPiwByhU9SrVBrYAiQggCKz4UAWQUCfPGQTsCG0IwMzM+AwFfE6U520EXHxZCgGo8PvEAQRIZz/BBNdcTQqCbRD7PAEAQBRoIQtaD"
            + "E0LIzEw+pACyDUHzD0LEDRlCqBxaPk0AeQjRwhlCZhAnQtBNYj4dAJQFSA4yFA0AAJhBFQAADEIdAAC4QSUAAJBBQIDFooWdBirtAQoQO50EgEUdRRKzjDGk5nxL5BIGCAEQARgCGgYIABABGAAgACqpAQoQDVl+"
            + "R2qtRDODwOW3mQkpaRGvRDhCpRvHQRgHIKMCKNwNMhLEw8M/6AMJACGTlXwAAIA/AAA6cDqQRkJS7g9CAAAAAPIAVxLP6EVCZboYQgDNzDwaAbYUpjdHQgwzIULAR2E9FwGMFCMpSkLjLzBCMAaBPQcBlhMjc0xC"
            + "0s1AQqCZmT3SAGYQd2lOQurEUEJgObQ9fQBeC/RaUUL3Gl9C0MzMPSIA4gUyFA0AAEBCFQAACEIdAAAAQSUAAMhBQODEht+rByr+AQoQKrPQkfvFTxOgbslh2FsvxRIGCAIQARgDGgYIABABGAAgACq6AQoQ6q6S"
            + "xp4hRgy8XeT27bumxRFn1lJCpRvHQRgIIKMCKNwNMhLEw8M/6AMJACGTlXwAAIA/AAA6gAHJz35CfJICQgAAAADIANQPn4p7QsF190GAm0Q85ACCEXWPekLzhgRCQJHtPOkAxhF1j3pCKTYSQsDMTD3UAJEQ4DZ7"
            + "QuhPHEKg8309pwDhDciFfEKbaSZCcGiRPXwARwteKH5CToMwQsDKoT1OAIcIWA+AQjGAP0IALbI9IQDUBTIUDQAAdEIVAADoQR0AAMBAJQAAsEFAoL6kiaYGKv4BChAM6RbSnSVPAbeGZH5tDxH7EgYIAxABGAQa"
            + "BggAEAEYACAAKroBChCsVJ3Pnp1LgL9Ym4ixi0K6EYhLakKlG8dBGAggowIo3A0yEsTDwz/oAwkAIZOVfAAAgD8AADqAAYyehULueiNCAAAAAMEAYg+1mYZCplUbQgATgzsGAY8TCbWJQiPAF0LAm8Q8GAGZFDwf"
            + "jkLuxRZCoO8nPQgBrBMEB5NC7sUWQqAWWT3TAIAQLkyWQi9hGUIQK4c9gACICxbAmEKy9hxCUI2XPUYAEAjMOJpCrYAiQqDvpz0VAB8FMhQNAACCQhUAABBCHQAAcEElAAAAQUCghN62jQcqrgIKEDome1sN4E5/"
            + "lWxzx0aoMZASBggEEAEYBRoGCAAQARgAIAAq6gEKEEEuOmLRp0E/jY2DNBowZLwR/rmAQqUbx0EYCyCjAijcDTISxMPDP+gDCQAhk5V8AACAPwAAOrABhyN/Qql/XEIAAAAAsgCIDlBncUKpf1xCABODO18B2Rjy"
            + "gH1CqX9cQmCNFz18AZEaOKiDQj4sXEIgL109egFxGiqLiUL8kFlCwPN9PVMBJBiefIxC8O9XQnBokT0EAWcTG26PQuROVkKgmZk92QDXEG+JkkLYrVRCwMqhPa4ARA5YbJhCwGtRQvD7qT2CAKQLi7GbQqnKT0KA"
            + "arw9JgAoBgjtoEL820xCsJvEPQ0AoQQyFA0AAGxCFQAAREIdAADIQSUAABBBQOCngoD7BiqYBQoQzX0pagMVS6mvPudNsOGYoBIGCAUQARgGGgYIABABGAAgACrUBAoQfvAq7ectRoS5e4fTJ5k5oRGuYptCpRvH"
            + "QRgeIOMCKJwNMhDEw8M/6AMJAJV8AACAPwAAOpwEThCrQnDxAEIAAAAA+AAhk7MSmLyqQva660EA16M7BwE7k5YTA2SrQsAL3kEACKw8EgHqkzoUV3+uQjzV2EGAQws9DAEwlOsT1JWyQuQ51kEgCCw98ABTlDgS"
            + "nce5Qk7s1EHAzEw93QCVlBgR0DG+Qrrg1kEgBoE9ugCmlAQPI03BQgKn4EFwaJE9sgColIEOwe/CQrtK8EEwCKw9sgColIEOmBnDQnDxAEJQObQ9vAColCAPwe/CQu0QCkKgm8Q91QColJMQAnfBQpSJEkIwCtc9"
            + "7QColAcSjoW+QlNEHkKAbOc9BwGolJ0ThWC9QvobJUK4HgU+CAGolKETbvnAQlpvJUJQuB4+CgGolL8TNbzEQlpvJULoUTg+IAGolBUVXwHIQt0EKUIQg0A+RQGolEgXiSHKQqGULULIzEw+ZQGolDoZBzjOQlSu"
            + "N0IYBFY+rQGolIsd76vQQuPkPEJgZmY+0AGolJcfrknTQvsmQEKwnW8+5AGolM8g2I7WQgfIQULYznc+6wGolDohFEPdQgfIQUIAAIA+6gGolCUh3CriQk44PULwp4Y+sQGolL8dm8jkQjb2OUKAwIo+WQGolIQY"
            + "OZDnQh60NkLMzIw+JAGolFQVY9XqQvtxM0IoXI8+2gColOUQAZ3tQrnWMEJwaJE+mAColO4MdY7wQkLiLkK8dJM+UQColLkIqB32QqGULUIEgZU+JQColA4GMhQNAACmQhUAAMhBHQAALEIlAADQQUDg/6Da0AUy"
            + "FA0AAAAAFQAAAAAdAAAAACUAAAAAOgYIABAAGABCEHjUq+0PyU2Vo9NqTnb+rXE="
        ,
        expectedStrokeCount: 6,
        expectedBounds: CGRect(x: 19.0, y: 25.0, width: 107.0, height: 34.0)
    )

    static let multiLine = Sample(
        name: "multiLine",
        note: "여러 줄에 걸친 필사",
        base64:
            "AXdyZPABAAgAEhAAAAAAAAAAAAAAAAAAAAAAEhCvNJLG7rZIfqM1SOG0NR5rEhD/UTA1Dc5Cbr46SYzfc0BPGgYIABAAGAAaBggQEAEYEBoGCBAQAhgAIjQKFA0AAAAAFQAAAAAdAAAAACUAAIA/EhFjb20uYXBw"
            + "bGUuaW5rLnBlbhgDQSK8gc3sreW/Kq0DChB9Ad96MgVNqp8cLxOLat/vEgYIABABGAEaBggAEAEYACAAKukCChA3tJZsX9tOdrU9oKP+1jJrEc7jAoqDuMdBGBEgJyjYDzIQ6AMAAIGe5I7/fwAAgD8AADqyAo0D"
            + "ukGrbhNCAAAAAMh7LEDdALExskEl6QtCABKDOz67LkB8AbExskFzVhhCoO8nPcKkMED9AV1/s0EIcCRCYJFtPf0dMUAgAp8atkFl+ipCACuHPfRKMUAtAgoPuEExLDJCcGiRPQx1MUA7AmSqukHZYjhCkJmZPaeK"
            + "MUBBAs+evEGAmT5CwMqhPYiYMUBGAv8iw0E1ZElC4PupPXueMUBIAgVOykFRjFJCMF66PSS1MUBPAuIf0kEZdFdCwMzMPSLCMUBUApvD4UGyFllCEC/dPU23MUBQAtFy70FCb1hC0M73PT68MEAEAgci/UHAM1NC"
            + "kBgEPg2BL0CvAfikCULPBktCuEkMPnC7LUA6AYfbDkK8ckZCmJkZPipLK0BjALdfFULPj0BCwMohPgP0KkAMADIUDQAAqEEVAAAIQh0AAJBBJQAAsEFA4IC2xdoGKvMFChDenyGrM71Fr52vXTng8Fd+EgYIARAB"
            + "GAIaBggAEAEYACAAKq8FChCJXDuRw3FFP4W6w1QWfHn3ERHDIoqDuMdBGCMgJyjYDzIQ6AMAAIGe5I7/fwAAgD8AADr2BCneHEJAiB9CAAAAAOgIMEC+ASneHEI2tSdCoPN9PfaxL0CjAfOEHULe6y1CcGiRPV/f"
            + "LkBpAf8lH0JkcTVCwMqhPWArLkA6AeJtIUKJ40BC4PupPWCwLUAaAVliI0KlC0pCoJvEPeZwLEDDADuqJUIrkVFCEC/dPWX6K0CeAH1FKEJfX0pCUOMlPpblLkBqAZWHK0L+1ENCwEs3Pkj3LkBvAVkXMEKhSj1C"
            + "OLRIPoaBLkBQAehNNULZYjhCiBZZPoj9LEDrAAwxOkI7djRC+H5qPnOgK0B+AKcIQULChDFCkBiEPpQSLUDxAAFFRUJ3TzxC9P2UPjlpL0COAXg5R0LY2UJCjJeuPsY2LkA9AULgR0J7EElCfD+1PuGvLEDWABmH"
            + "SEK86VBCWGS7PnGjK0B/AITaSEJoallCAADAPuVCK0BTAITaSEI5nGBCkBjEPtgMK0AuAITaSEK7IWhC3CTGPrj9KkAeAELgR0KoQ2FCqPHSPt3zKkAKAELgR0LTx1dCmJnZPrP5KkAYAELgR0Jt805CdL7fPnWI"
            + "LEDKABmHSEILaUhCZGbmPvt4LkBOAWYiS0JoMkJCRIvsPraaL0CjAR+yT0KhSj1CMDPzPlE8MEDRAU82VkKTtjhCEFj5PnVzMEDiAcC0XULUGDZCAAAAPyWPMEDrAfzZZUIaxTVCbhIDP4rhMEAIAs0KbEKKbDZC"
            + "ZmYGP1kkMUAiAvHtcEKhSj1C1HgJP1kkMUAiAj6Jc0JNy0VCzMwMP72aMEDvARXRdUKzn05COt8PP59lL0CUAcEed0KE0VVCMjMTPwZZLUAMAW4NekK3YFtCokUWP2+aK0CAAEgfMhQNAAAYQhUAABhCHQAA0EEl"
            + "AACoQUDAl9X2rwYq0wMKEGTh+EI2x08ZmbS1FLbqh/gSBggCEAEYAxoGCAAQARgAIAAqjwMKEFsSnyPZlETzoIg7T7jM13QRObV5ioO4x0EYEyAnKNgPMhDoAwAAgZ7kjv9/AACAPwAAOtYCkROCQtShK0IAAAAA"
            + "5VIuQF4BC0OBQjt2NEJACKw80r4xQFMCN2GDQt0jRUJQN4k9694wQAsCvTGEQvQBTELAyqE9+vIuQIcBQwKFQsAzU0Lg+6k96zYuQFYBydKFQgENW0IQLbI9gYAtQCYBBc2GQmfhY0KAarw9grUsQOwA1XOHQu5m"
            + "a0Kgm8Q9gSYsQL8ATGiJQt8KfkLQzMw977ArQJIA87WKQg7ygkJAYOU9sQArQCYAo9+KQr9Zf0KQGAQ+ex8rQEQAo9+KQsgsd0JwaBE+QzEsQMIAo9+KQmJYbkKYmRk+vRQuQFQBo9+KQtzSZkLAyiE+0yIwQN0B"
            + "o9+KQlADXUIQAis+kY8xQEQCDjOLQsp9VULISzc+9r8xQFMC6nqNQv1LTkKom0Q+sdAwQAwC6D+QQl9fSkJg5VA+ZQgtQAsB1iiUQrxyRkKIFlk+AQcrQC8ASA8yFA0AAHxCFQAAJEIdAABAQSUAAMhBQMCC3oaW"
            + "BiqEBQoQtERs3xzrSTGvZv317DjrGBIGCAMQARgEGgYIABABGAAgACrABAoQgzGzowvCRc2C+JdMwk2uAxHXwCaMg7jHQRgaIKcBKNgOMg7oAwAArp3/fwAAgD8AADqIBCG0oEIHqDtCAAAAAKIyLUDLAGmea4qg"
            + "QqHTMkIAE4M7OSEtQMcASp4qGqVC3ustQqDvJz0AQi1A0ABKnm96qkI//ylCIC9dPQlELUDQAEqe0ZKtQqZcKELA8309lUItQNAASp7p1LBCDbomQhArhz0PQC1AzwBKngcXtEItayVCMFyPPcYqLUDJAEqeiqy3"
            + "Qk4cJEKgmZk9s/ssQL0ASp6Q175CmMgjQsDKoT2u2CxAtABKnl5DwkLHDSdCQF66PUqkLECmAEqeE23CQpyJMEIA/tQ963UsQJoASp4WqL9CIw84QnCR7T1PPCxAiwBKnpMSvELwQD9CAAAAPmcsLECHAEqexqa4"
            + "Qm18REIoMQg+sRssQIMA/53I4bVCC2lIQlBiED4Z/CtAegCEnb97sUIe/UxCyMohPmCDK0BWAN6cBxe0QuZtR0LwfD8+JvsrQHoAuJyZiLZCSIFDQmDlUD5JWixAkwCVnOAjuUKqlD9CiBZZPjWuLECpAGCcJYS+"
            + "QrixOUKwR2E++kUtQNEA0Jvz78FC2WI4Qiiwcj59ei1A4ABWm+HYxUKTtjhCAACAPsCHLUDjAMGajsfIQhDyPUIoMYg+eYMtQOIAaJphM8xCBx9GQhjZjj6ovyxArQAXmsRLz0IUs0pCQAqXPsZ+K0BVAOuZkbfS"
            + "Qj6uS0Iwsp0+SfQqQAkAwJlIFjIUDQAAnkIVAAAgQh0AAOBBJQAAQEFA4NmopOQEKq8CChDKiELpPytPVqXH8U6eD/b6EgYIBBABGAUaBggAEAEYACAAKusBChC13Ma88Q5GwIIPzDCkOWkDEQzJWYyDuMdBGAog"
            + "JyjYDzIQ6AMAAK6da5H/fwAAgD8AADq0AcQA3EKGcxJCAAAAALUoLUDZAOK42UJvlQtCwMzMPOG2LUD+AH1l2UKGcxJCoO8nPdHdLUAIAX1l2UJTpRlCYJFtPdi6LUD/AOK42UKPfiFCACuHPYlFLUDgAIkG20KF"
            + "qylCkJmZPfKNLECxAJWn3EIMMTFC4PupPRHwK0CFAKFI3kLZYjhCMF66Pf5mK0BWAPe/30Jf6D9CwMzMPRUEK0AgAJ4N4UKcwUdCEC/dPb7zKkAIADIUDQAA1kIVAAAIQh0AAOBAJQAAiEFA4JHolLsGKsMCChDs"
            + "Pqjd1c9Py7N+Dxp5b3Y9EgYIBRABGAYaBggAEAEYACAAKv8BChDJnfFNxy9AbLUV08QmjFT2EXTUcYyDuMdBGAsgJyjYDzIQ6AMAAK6da5H/fwAAgD8AADrGATXK1kKJ40BCAAAAAFGDLEC+AGqZ0EKJ40BCAP5U"
            + "PIgQLUDlADLazELY2UJCwMzMPL3wLUAeAXywzELvt0lCgGo8PU9ZLkA6AZTyz0KNpE1CcGiRPehVLkA5AbI000KS7k9C4PupPSCiLUAKAZod10JxPVFCgGq8PQzBLEDPAD4w20Lh5FFC0MzMPQcCLECYAJJs30Lh"
            + "5FFCEC/dPcdkK0BeABUC40Lh5FFCsJ3vPYMIK0AoAC1E5kJMQlBCAAAAPsvzKkAJAEgHMhQNAADKQhUAADxCHQAAgEElAADgQEDgu5DSxQQqhgIKEN4uanRIoU/xupO7QzqJA9cSBggGEAEYBxoGCAAQARgAIAAq"
            + "wgEKEI4SvXH4H0gIgWDZ2D2/+0ARgZeNjIO4x0EYByCnASjYDjIO6AMAAK6d/38AAIA/AAA6jAFsLvFCgeocQgAAAAAuRS1A2QBrkWCN70JuzSJCwMxMPQFGLUDZAGuRPxDvQtShK0JgkW09Hz4tQNcAa5HavO5C"
            + "638yQnBokT1xvSxAtgBgkdq87kKhSj1CwMqhPdc2LECSAEOR2rzuQrgoREIwXro96IsrQF8AQ5FLsfBCpQtKQsDMzD3+MitAOwBDkTIUDQAA7EIVAAAYQh0AAIBAJQAAYEFAwLqIt9sEKvgBChA6JSW8RJZOKYfY"
            + "19LTKY60EgYIBxABGAgaBggAEAEYACAAKrQBChBgD458O49NfpDhmqkaAeZJEbr0oYyDuMdBGAcgJyjYDzIQ6AMAAK6d1JD/fwAAgD8AADp+nLL3QiSYLUIAAAAAkrQrQGEABMv6Qrl5IkLAQ4s814gtQOIAPYr+"
            + "Qrl5IkKAajw9YNstQAgBzjMCQw26JkKgmZk9fLctQPUAJ6sDQ6ZcKEKwm8Q9W/crQHMAWTcFQ4WrKUJACtc94j0rQDkAglUHQ6+mKkKQbOc9CPsqQBIAMhQNAAD0QhUAABxCHQAAcEElAADAQEDgo/v34gYq5gEK"
            + "EIVtWilvWUJ2sUV4EEBWfR4SBggIEAEYCRoGCAAQARgAIAAqogEKEFNln50E2kmQhdIWQYUmNXMRSnq8jIO4x0EYBiAnKNgPMhDoAwAArp0xi/9/AACAPwAAOmyCVQdDUy4PQgAAAAAs8yxAuwDw4wRDb5ULQgAS"
            + "gzsC5SxAtwAWzwRD9hoTQkCNFz3mzixAsQAWzwRDgeocQmCRbT3OLSxAiADL+ARDvsMkQiBcjz2EVStARgDBigVDc44vQsDKoT1K/ypAGAAyFA0AAANDFQAACEIdAADAQCUAADBBQICY4My6BSqVBgoQdMFt1sCL"
            + "QmWi31S9/bjYoxIGCAkQARgKGgYIABABGAAgACrRBQoQ0FKyr8m0RcaYwqI5HXnNoRGitNGMg7jHQRglICco2A8yEOgDAABknjGL/38AAIA/AAA6mgVZNwVD4qw6QgAAAAB00CxAsgAvGQNDIw84QkAIrDw0wSxA"
            + "rgDw4wRDIw84QiAvXT00wSxArgCNwwZDIw84QnBokT0VoCxApQBOjghDAl45QvD7qT0DbyxAmQBaLwpDxkU+QrCbxD3mcCxAmQAG6wpD/tRDQpBs5z3ozyxAsgAG6wpDX19KQgiBFT5gOi1AzgA6dwxDdsZGQmDl"
            + "UD7vkCtAWwBGGA5DPzdBQkA1Xj4cEStAJQCYIRBDSAo5QpBsZz6X8ypABwA7bxFD638yQnC8dD4I8ypABQB0aRJD9VIqQhSDgD7QHitALQCS5hJD/yUiQkw3iT5t2CtAcADzyxNDx5YcQtD3kz6CiSxAnwBxLhVD"
            + "mVEZQujQoj4orCxAqACluhZDmVEZQsT1qD5z+SxAvAAz+RZDaoMgQrSdrz78Ui1A1AAz+RZDFgQpQtzOtz7Cdi1A3gAVfBZDA+cuQsh2vj56fC1A4ADZgRVD+RM3QlyPwj72hi1A4wAuxhRDMaM8Qkw3yT7ihS1A"
            + "4wDrXRRDHoZCQqwc2j5WoC1A6wD3/hVDrt5BQpzE4D5WoC1A6wDXRhhDxkU+Qnzp5j5vfi1A4QC9/BlDMaM8QmiR7T4QPC1AzgDnGhxDlwA7Qvyp8T5HEi1AwwAbpx1DlwA7QtzO9z7J1C1A/QD2ux1D+YpBQq5H"
            + "AT+iSi5AJAHYPh1DnMFHQuj7CT9X5C5AWQHYPh1DApZQQnwUDj/+HC9AbgFXoR5DMNtTQnRoET+CYi9AkQGXziFDoIJUQgaBFT/YYy9AkQHIWiND4eRRQkjhGj8HBi9AZQEQ9iVDPq5LQhwvHT9vJy5AHwHRwCdD"
            + "LBpHQopBID9mGixAlABItSlDHoZCQtRNIj9VGytAMgAyFA0AAAJDFQAAFEIdAAAkQiUAAIhBQOCdj73VBiqbBAoQ93gqeqgVS7aTNI1RHHeZ7xIGCAoQARgLGgYIABABGAAgACrXAwoQIOnMvBp4S2m6UFvWyrfF"
            + "gBEHmUqNg7jHQRgXICco2A8yEOgDAAC0njKJ/38AAIA/AAA6ngOOqk9DeBclQgAAAAChSC1A0gBpv09D0OAeQgASgzsTJS1AyQBfUVBDmVEZQoD9VDxKFi1AxQCaS1FDi70UQgAIrDwAlC1A6ADsVFNDDYIPQkCR"
            + "7Twc4i1AAQE7XlVDLjMOQiAILD1j5S1AAgFH/1ZDntoOQgAvXT2O7C1ABAEiFFdD2rMWQsDKoT21xy1A+ABSbVZDG40eQlA5tD1UfS1A4QCYEFRD1KErQnBqvD3yXS1A2AD7MFJDhSI0QvD91D34Ey1AxABE1E9D"
            + "oUo9QoBs5z2p4yxAtwB4m05D+YpBQgAAAD7WlyxApACR5UxDdsZGQkg3CT5CfCxAnQDyyk1DOu0+QnjpJj6kfytAVQAmV09Dabs3QsBLNz6heytAVAAy+FBDUt0wQnhqPD5IuytAaAASQFNDhaspQqCbRD6nXixA"
            + "lQC1jVRDV2YmQmDlUD5l+yxAvgDnGVZDmMgjQqgcWj5/oy1A7AAJylhDmMgjQmBmZj6T1y1A/QBJ91tDYLAoQgAAgD6LeC1A4ABOKl5DH04rQoDAij43FStAKABIFjIUDQAATEMVAAAIQh0AAKBBJQAAiEFA4JL4"
            + "npgHKq0CChBu4t8oy3xFiaSJnuAcuHA0EgYICxABGAwaBggAEAEYACAAKukBChDqDv4jSPdOT7tD8kPRZ8nDEQ1SeI2DuMdBGAkgZyiYDzIO6AMAACmG/38AAIA/AAA6tAEAGWFDb5ULQgAAAADg1ixAtwC5ntgt"
            + "YUNYtwRCgBIDPIDFLECyAESf2C1hQ/Pi8UGAEoM8khkuQBQBEaDYLWFDyF4FQiAvXT2UUC5ALAERoNgtYUNvlQtCwMqhPd/zLUAHARGgjldhQzzHEkIQLbI9xGktQN0AEaBDgWFDeKAaQmCPwj1MqSxAqwARoPaq"
            + "YUP/JSJC8P3UPQ21K0BoABGg9qphQySYLUJAYOU91hkrQCwAEaAyFA0AAGBDFQAA8EEdAABAQCUAAHBBQKDjsd6wBiqLAgoQdDxRGEoBQAG3rbisPnrE0RIGCAwQARgNGgYIABABGAAgACrHAQoQ9mJJYG6BSMym"
            + "ijvdGj8LcxHa5ZGNg7jHQRgIICco2A8yEOgDAAARoCmG/38AAIA/AAA6kAFqr1lDwfs7QgAAAAA7SC5AKwGD+VdDwfs7QuClGz0dzS5AUgGD+VdD2NlCQsBHYT262i5AVgEnR1lDVhVIQqCZmT3OTy5ALQFb01pD"
            + "FLNKQmA5tD3HLi1A4QCq3FxD9AFMQrCbxD3STyxApgDjm2BDrlVMQkAK1z01ZStAWQBPImNDPq5LQrCd7z0G9SpADAAyFA0AAFdDFQAAOEIdAABgQSUAAMBAQKDv67WpBCqdAwoQYiJzDj6sQdOdW811lI9k8xIG"
            + "CA0QARgOGgYIABABGAAgACrZAgoQqEBbZmSZT/2/G8tDd4yXoBEqVKmNg7jHQRgQICco2A8yEOgDAAARoKaD/38AAIA/AAA6oAJi7mtDlAcXQgAAAABw9SxAwQCCpmlD7dAQQoASgzybpy1A8QCy/2hDJGAWQqDv"
            + "Jz1ivi1A9wBvl2hDx5YcQmCRbT1ivi1A9wDB22dDeBclQgArhz3VsC1A8wCtzGZDUt0wQqCZmT03iS1A6AD/EGZD4qw6QhAtsj1kES1AyQBM52VDrt5BQkBg5T0MFixAhwCjXmdDOu0+QgAAAD4AuCtAawAhwWhD"
            + "Al45QsBJDD6dECxAhQBEcWtD3ustQgiBFT7tUi1A2gDC02xDFgQpQljjJT7L3S1AAQER3W5Dbs0iQqAaLz7bLS5AGwFrVHBDsC8gQvB8Pz7CLi5AGwEsH3JD+tsfQtDMTD7A2i1AAAExUnRDsC8gQkA1Xj7Y1CtA"
            + "dABIDjIUDQAAZUMVAAAMQh0AAIhBJQAAYEFAgNaO1aYFKoUCChDPKn++wHJE36ZxngEMToaWEgYIDhABGA8aBggAEAEYACAAKsEBChB+HYLDL0ZIZ63r3RwGY/amERai042DuMdBGAcgZyiYDzIO6AMAAKaD/38A"
            + "AIA/AAA6jAGteXhDQVD+QQAAAACoqy1A7wAyoJ7YdkNYbfhBABODO1QvLkAhAUWgEJp2QwnBAkLgpRs9ljAuQCIBRaAQmnZDT+QMQiAvXT1K1S1A/ABFoBCadkOLvRRCUDeJPbFRLECSAEWg6652Q4HqHEKgmZk9"
            + "sFkrQEgARaDrrnZDV2YmQvD7qT2n+ipAEwBFoDIUDQAAdUMVAADwQR0AAKBAJQAAUEFA4Ij2meAEKpcGChB5o6Isjc5O2r4EfPJ5NTvEEgYIDxABGBAaBggAEAEYACAAKtMFChAhiuUdgQdPTbevxKyU0EQ5Ec42"
            + "542DuMdBGCUgJyjYDzIQ6AMAAEWgpoP/fwAAgD8AADqaBdOncENyBTpCAAAAADqyLEC2AHwwb0MVezNCQAisPF3DLEC7APuScEPiNTBC4KUbPXzZLEDAALpdckOTPy5CIC9dPXzZLEDAAEdhdUP+nCxCIAaBPTzC"
            + "LEC6AOFAd0P+nCxCkJmZPXB+LECpAA1feUO08CxCMAisPeKNLECtAJMvekMxLDJCoJvEPZNeLUDjAG5EekO4sTlCsJ3vPSxhLkAsASvceUNf6D9CkBgEPhdkLkAtAa15eEN7EElCCIEVPpHxLUAKASvceUMn0ERC"
            + "gGo8PsDoLEDEADd9e0PGRT5CyMxMPnjtK0CAAEuMfEMCXjlCqBxaPkE4K0A/AIaGfUOFIjRC0E1iPioJK0AjAE+/fkOTPy5C+H5qPsP6KkAVAEDjf0OmXChCSLZzPuj7KkAWAN+igEMpISNCAACAPscjK0A1AB9U"
            + "gUNhOR5CpJuEPjzUK0B5ABIvgkMI+RlChMCKPvIbLECOAAUKg0NzVhhCzMyMPhdyLUDoAJj/gkNJ0iFC5KWbPo7nLUAHATRjgkO08CxCZGamPi11LkAzAfH6gUOFIjRCoBqvPh+WLkA/Ac/GgUOqlD9CJNu5PnKY"
            + "LkBAAeAeg0Nf6D9C8KfGPuOILkA6AfUthEMQ8j1CGNnOPqgzLkAeAVFchUPirDpCvHTTPo32LUAMAdN1hkMjDzhCUI3XPtKlLUD1AKFlh0NEwDZC5KXbPuZdLUDiALsriEOKbDZCiEHgPmuTLUD0AOTNh0NWnj1C"
            + "oBrvPgbCLkBWAVpGh0OOLUNCNDPzPrFiL0CFAaUch0NfX0pCJNv5Pg7xL0C4AeAWiEP0AUxC+FMDP2zpL0C1ATiOiUP0AUxCjGwHP0mbLkBLAcBeikP0AUxCqMYLP3o5K0BJAEgfMhQNAABuQxUAABRCHQAAIEIl"
            + "AABwQUCg/rKhpwYq9wMKEE57FKFeSk/Fj2MBf76gWeQSBggPEAIYABoGCAAQAhgAIAAqswMKEOO0MMBoCUG9ovoCnc1Cfl4Rv+9XwYO4x0EYEyBnKJgPMg7oAwAAa5D/fwAAgD8AADr8AnNaZ0JdmVlDAAAAACmq"
            + "LECoADaJnVVoQiwNWENQNwk+lUItQNAANomv6WxCv4ZVQxACKz7tci1A3QA2iW6Hb0LZ0FNDgGo8PoqRLUDmADaJViBzQtSdUUOom0Q+75otQOkANolgtHdCR5pOQ9DMTD5qpS1A7AA2iR5SekKtukxDGARWPgyw"
            + "LUDwADaJUZd9QluxSkOwHFo+vrstQPQANolCboBCfGlIQ0A1Xj5OxC1A9gA2idcQgkKgIUZD2E1iPnjLLUD5ADaJcLODQsDZQ0NoZmY+tM0tQPoANonlf4VCUFNBQyCFaz5lzi1A+gA2icTOhkLcXj9DuJ1vPlrW"
            + "LUD9ADaJxPOHQvaoPUNItnM+Et8tQAABNonu7ohCwRw8Q9jOdz6w7S1ABQE2ic09ikIHwDlDcOd7PigHLkAPATaJPeWKQtYzOEPwp4Y+qXYuQDQBNomtjItCrBU2Q/gonD6gly5APwE2iZEAjkJOazJD1E2iPqM4"
            + "L0CHAYSJSBAyFA0AAGBCFQAAMUMdAACAQSUAAChCQMDvuP+mBTIUDQAAAAAVAAAAAB0AAAAAJQAAAAA6BggAEAAYAEIQPgCs0MvaQm6aoDEneVaAEQ=="
        ,
        expectedStrokeCount: 17,
        expectedBounds: CGRect(x: 21.0, y: 30.0, width: 257.0, height: 189.0)
    )

    static let detectable = Sample(
        name: "detectable",
        note: "첫 획이 절 원점 20pt 안에서 시작 — 판정이 발동하는 소수 사례",
        base64:
            "AXdyZPABAAgAEhAAAAAAAAAAAAAAAAAAAAAAEhDtvqWUhTxLTYAjQkWHX6ItGgYIABAAGAAaBggBEAEYASI3ChQNAAAAABUAAAAAHQAAAAAlAACAPxIUY29tLmFwcGxlLmluay5wZW5jaWwYA0FaOx1/eHjovyrS"
            + "AwoQZFCaLSUASqu3V9MCpVwdWBIGCAAQARgBGgYIABABGAAgACqOAwoQVwAYu/aUQG2mIYnjZUlvahFEivVCpRvHQRgTIOMCKJwNMhDEw8M/6AMJAOKAAACAPwAAOtYCN5m2QVETtkEAAAAAogBklIsNGI6nQWMq"
            + "skEA16M7SAFklIAXdZaUQSx7pEHAQ4s8fwFklMQaa/CkQSx7pEHgpRs9hQE2lBob3oW6QVz/qkHAR2E9hQEYlCEbCfPGQUvorkEwBoE9gwEPlAcbV2DTQTnRskFQN4k9ggEKlOsaps3fQfJgt0FwaJE9fQEKlKUa"
            + "HDcCQigQxUGgmZk9eAEKlF0a7bILQnzWzkFgObQ9XAEKlKoY1t8TQppD2UGwm8Q9PAEKlLwWpxEbQtDy5kFACtc9CAEKlKATkKoeQlQ990GQbOc9ygAKlPcPuqUfQpmyBkLgzvc9hwAKlPELuqUfQp/dDUK4HgU+"
            + "QwAKlNwHuqUfQtVhFEJQNwk+KQAKlFQGkKoeQp+SGkLgTw0+FwAKlEIFkGAcQmrDIEJ4aBE+CAAKlF8Ep30WQvODK0IIgRU+BwAKlEoEMhQNAACIQRUAAJBBHQAA0EElAADgQUCghf21mwQyFA0AAAAAFQAAAAAd"
            + "AAAAACUAAAAAOgYIABAAGABCENsLAxF9CUOal5Lsx5yb8a0="
        ,
        expectedStrokeCount: 1,
        expectedBounds: CGRect(x: 17.0, y: 18.0, width: 26.0, height: 28.0)
    )

    static let all: [Sample] = [single, aboveOrigin, wideLine, multiLine, detectable]

    /// `normalizedForVerseRect` 의 판정이 **발동하지 않는** 샘플들.
    ///
    /// 판정은 `strokes.first.renderBounds` 가 `rect.origin` 에서 두 축 모두 20pt 이내일 때만
    /// 성립하는데, 실제 필기는 대개 그 조건을 벗어납니다.
    /// 추출한 225 건 중 **29% 만** 발동하고 나머지 71% 는 절대좌표여도 복원되지 않습니다.
    static let undetectable: [Sample] = [single, aboveOrigin, wideLine, multiLine]

    /// 1.2.0 `CombinedCanvas` 가 저장했던 **절대좌표** 형식을 재현합니다.
    ///
    /// `normalizedForVerseRect` 는 절대좌표를 로컬로 되돌릴 때
    /// `translationX: -rect.minX, y: -rect.minY` 를 적용합니다.
    /// 그 역변환이 곧 "1.2.0 이 저장했을 형식" 입니다.
    static func absoluteVariant(of drawing: PKDrawing, verseRect: CGRect) -> PKDrawing {
        drawing.transformed(
            using: CGAffineTransform(translationX: verseRect.minX, y: verseRect.minY)
        )
    }

    // MARK: - 절 rect 시나리오

    /// 장 **맨 위** 절. `normalizedForVerseRect(tolerance: 20)` 가
    /// 로컬과 절대를 구분하지 못하는 구간입니다.
    static let rectAtChapterTop = CGRect(x: 0, y: 8, width: 360, height: 120)
    /// 장 중간 절.
    static let rectAtChapterMiddle = CGRect(x: 384, y: 480, width: 360, height: 120)
    /// 시편 119편처럼 깊은 위치의 절.
    static let rectDeepInChapter = CGRect(x: 384, y: 5200, width: 360, height: 120)
}
